# spec: specs/emoji-checkmark-reaction.md
"""Generated by the discord-test-generator flowchart. Do not edit by hand."""

from __future__ import annotations

import time
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .helpers import Discord


CHECKMARK_NAMES = ("\u2705", "\u2611\ufe0f", "\u2611", "\u2713", "white_check_mark")


def test_bot_adds_checkmark_reaction_to_processed_message(
    discord: Discord, master_channel: str, warmup: None
) -> None:
    sentinel = f"REACTION_CHECK_{int(time.time() * 1000)}"
    msg_id = discord.send(master_channel, f"Say exactly: {sentinel}")
    discord.wait_for_bot(master_channel, after=msg_id, timeout=60.0)
    time.sleep(2)

    resp = discord._bot.get(f"/channels/{master_channel}/messages/{msg_id}")
    resp.raise_for_status()
    msg_data = resp.json()
    reactions = msg_data.get("reactions", [])

    has_check = any(
        r.get("emoji", {}).get("name") in CHECKMARK_NAMES for r in reactions
    )
    assert has_check, f"No checkmark reaction found. Reactions: {reactions!r}"
